### PR TITLE
Add research consent to reg form + cookie banner update

### PR DESCRIPTION
**Pull request by dalehurwitz**

### CODE REVIEW

**Comment by andrewoh531** [comment]
Can you fix up the vertical alignment for the checkbox? Seems a little too high in comparison to the text. 

Other than that looks good from me. 
screen shot 2018-12-11 at 11 52 22 am

**Comment by dalehurwitz** [comment]
> Can you fix up the vertical alignment for the checkbox? Seems a little too high in comparison to the text.
> 
> Other than that looks good from me.
> screen shot 2018-12-11 at 11 52 22 am

**Comment by dalehurwitz** [comment]
@andrewoh531 fixed checkbox styling

**Comment by jonathaningram** [comment]
@dalehurwitz 

image

I see the build has passed but the checkbox change didn't seem to go through?

**Pull request merged**
